packages:
  - packages/**
  - playground

catalog:
  "@vitejs/plugin-vue": ^6.0.1
  "@vitejs/plugin-vue-jsx": ^5.0.1
  "@vue/tsconfig": ^0.7.0
  typescript: ^5.8.3
  vite: ^7.0.6
  vue: ^3.5.18
  vue-tsc: ^3.0.4
  "element-plus": ^2.10.4
